on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose -f docker-compose-dev.yml up --build
      - name: Check running containers
        run: docker-compose ps -a
      - name: Check logs
        run: docker-compose logs web
      - name: Run tests with coverage
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web pytest