dist: trusty
language: python
python:
  - "3.7"

services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - docker-compose -f docker-compose.prod.yml run web python manage.py test
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master