version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_app.wsgi -b 0.0.0.0:8000
    env_file:
      - ./.env.prod
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=true"
