version: '3'

services:
  db:
    image: postgres
  migration:
    build: ./app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate'
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
  web:
    build: ./app
    image: django-toast
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration