version: "3.7"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:80
    env_file: .env
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: