# docker-compose.yml
version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
    - ENVIRONMENT = ${ENVIRONMENT}
    - DEBUG = ${DEBUG}
    - DATABASE = ${DATABASE}
    - DJANGO_ALLOWED_HOSTS = ${DJANGO_ALLOWED_HOSTS}
    - SECRET_KEY = ${SECRET_KEY}
    - SQL_DATABASE = ${SQL_DATABASE}
    - SQL_ENGINE = ${SQL_ENGINE}
    - SQL_HOST = ${SQL_HOST}
    - SQL_PASSWORD = ${SQL_PASSWORD}
    - SQL_PORT = ${SQL_PORT}
    - SQL_USER = ${SQL_USER}
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=toastapp
      - POSTGRES_PASSWORD=toastapp
      - POSTGRES_DB=toastapp_dev

volumes:
  postgres-data:
