name: Push Container to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Prod Docker container
        run: docker build -f app/Dockerfile.prod -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Login to Heroku Container registry
        env:
          HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      - name: Push Docker container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release Docker container
        uses: actions/heroku@master
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login && heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
