on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Docker-compose chmod
        run: |
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker image
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          DEBUG: ${{ secrets.DEBUG }}
          DATABASE: ${{ secrets.DATABASE }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          SQL_USER: ${{ secrets.SQL_USER }}
        run: |
          docker-compose -f docker-compose-ci.yml up --build -d

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests with coverage
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          DEBUG: ${{ secrets.DEBUG }}
          DATABASE: ${{ secrets.DATABASE }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          SQL_USER: ${{ secrets.SQL_USER }}
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          docker-compose -f docker-compose-ci.yml run web sh -c "pytest -s -v --cov --cov-report=html:reports/html_dir --cov-report=xml:reports/coverage.xml"
          docker-compose -f docker-compose-ci.yml run -e COVERALLS_TOKEN=${{ secrets.COVERALLS_TOKEN }} web sh -c "coveralls"
